title: LSM American Option Pricer
description: This project implements the Longstaff-Schwartz Least Squares Monte Carlo (LSM) algorithm for pricing American options in C++20
theme: minima
header_pages: []
kramdown:
  math_engine: null
  syntax_highlighter: rouge